# Generated by Django 4.0 on 2023-09-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0094_alter_userinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='type',
            field=models.CharField(default='leave', max_length=15),
        ),
    ]
