# Generated by Django 4.0 on 2025-01-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninetofiver', '0098_event_help_text_alter_event_ends_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportcontract',
            name='complexity',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (4, 4), (10, 10), (20, 20), (50, 50), (100, 100), (200, 200)], default=1, help_text='The chosen value will be used as a factor to divide costs based on the number of contracts and their relative "Complexity."'),
        ),
    ]
